### ISSUE TITLE
Proper pip package

### ISSUE THREAD

**Issue by CBockelmann** [ShenQianli/primal#1]
I'm not sure if this is still maintained at all, but a proper pip package would be greatly appreciated.

I'm currently using your implementation to show CS algorithms in jupyter notebooks for a lecture. The installation of your package could be much simpler if one could simply do it via jupyter magic
```
%pip install git+https://github.com/ShenQianli/primal.git
```

Then, any service like nbviewer or googles colab could load your code to use it in a notebook.

**Comment by ShenQianli** [comment]
Thanks for your interest in PRIMAL and your advice.

Now pip installation is available. Please run
```
% pip install pyprimal
```
in your notebook. Note the package name is _**pyprimal**_ as _primal_ has been occupied. 

Please do not hesitate to open another issue once you have any further questions.
